services:
  backend:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    env_file:
      - ./packages/api/.env
    ports:
      - "3001:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge